version: '3.9'
services:
  react-app:
    image: react-dev-image
    container_name: react-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - './src:/app/src'
